# -*- coding: utf-8 -*-
"""pipelines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6wym-Knb2AedVl7nS0Zuj3DtMI0lv5O
"""

import numpy as np
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

df=pd.read_csv('/content/Titanic-Dataset.csv')

df.head()

df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

X_train.head()

y_train.sample(5)

#imputation transformer
#jo column me value khali h unhe fillkrne ke liye
trf1=ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
    ],remainder='passthrough')

#one-hot encoding
#categorical data h isiliye numerical me convert krne ke liye

trf2=ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

#Scaling
trf3=ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

#feature selection
trf4=SelectKBest(score_func=chi2,k=8)

#train the model
trf5=DecisionTreeClassifier()

"""Create Pipeline

"""

pipe=make_pipeline(trf1,trf2,trf3,trf4,trf5)

pipe.fit(X_train,y_train)

"""explore pipeline

"""

pipe.named_steps

from sklearn import set_config
set_config(display='diagram')

y_pred=pipe.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



"""cross validation using pipeline

"""

